pull_request_rules:
  - name: automatic merge for Dependabot pull requests on master
    conditions:
      - author=dependabot[bot]
      - label~=dependencies
    actions:
      merge:
        method: squash
        strict: true
  - name: automatic merge on CI success when label is set
    conditions:
      - label~=ready to merge
    actions:
      merge:
        method: squash
        strict: true
  - name: delete merged branch
    conditions:
      - merged
    actions:
      delete_head_branch: {}